config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/public/items')

  devise_for :admins, path: 'admin', only: [:session], controllers: {
    sessions: 'admin/sessions',
  }
  devise_for :end_users, path: 'public', only: %i[session registrations], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }

  namespace :public do
    get 'mypage', to: 'end_users#show'
    patch 'mypage', to: 'end_users#update'
    put 'mypage', to: 'end_users#update'
    delete 'mypage', to: 'end_users#destroy'
    get 'mypage/edit', to: 'end_users#edit'
    get 'mypage/cancel', to: 'end_users#cancel'

    resources :items, only: %i[index show] do
      collection do
        get :search
      end
    end
    resources :cart_items, only: %i[index create update destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: %i[index show new create] do
      collection do
        get :confirm
        get :thanks
      end
    end

  end

  namespace :admin do
    resources :items do
      collection do
        get :search
        get :lists
      end
    end
    resources :end_users, only: %i[index show edit update]
    resources :orders, only: %i[index show update]
    resources :order_details, only: :update
  end

end

app/views/layouts/_admin_header.html.erb
<header class='l-header'>
  <span class='l-header__logo'>LOGO</span>
  <nav class='l-header__contents'>
    <% if admin_signed_in? %>
      <ul class='p-headnavi'>
        <li class='p-headnavi__item'>
          <%= link_to '商品一覧', admin_items_path %>
        </li>
        <li class='p-headnavi__item'>
          <%= link_to '商品登録', new_admin_item_path %>
        </li>
        <li class='p-headnavi__item'>
          <%= link_to '会員一覧', admin_end_users_path %>
        </li>
        <li class='p-headnavi__item'>
          <%= link_to '注文履歴一覧', admin_orders_path %>
        </li>
        <li class='p-headnavi__item p-headnavi__item--'>
          <%= link_to 'ジャンル管理', admin_items_path %>
        </li>
        <li class='p-headnavi__item p-headnavi__item--'>
          <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
        </li>
      </ul>
      <div class='p-searchBox p-searchBox--right'>
        <%= form_with url: search_admin_items_path, local: true, method: :get do |f| %>
          <%= f.text_field :query, placeholder: 'Search', id: 'item_autocomplete' %>
        <% end %>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<div class='l-footer'></div>

app/views/layouts/_public_header.html.erb
<header class='l-header'>
  <span  class='l-header__logo'>LOGO</span>
  <nav class='l-header__contents'>
    <ul class='p-headnavi'>
      <% if end_user_signed_in? %>
        <li class='p-headnavi__item'>
          <%= "ようこそ、#{current_end_user.full_name}さん!" %>
        </li>
        <li class='p-headnavi__item c-button'>
          <%= link_to 'マイページ', public_mypage_path %>
        </li>
        <li class='p-headnavi__item c-button'>
          <%= link_to '商品一覧', public_items_path %>
        </li>
        <li class='p-headnavi__item c-button'>
          <%= link_to 'カート', public_cart_items_path %>
        </li>
        <li class='p-headnavi__item c-button'>
          <%= link_to 'ログアウト', destroy_end_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class='p-headnavi__item c-button'>
          <%=link_to '商品一覧', public_items_path %>
        </li>
        <li class='p-headnavi__item c-button'>
          <%=link_to '新規登録', new_end_user_registration_path %>
        </li>
        <li class='p-headnavi__item c-button'>
          <%=link_to 'ログイン', new_end_user_session_path %>
        </li>
      <% end %>
      <div class='p-searchBox p-searchBox--right'>
        <%= form_with url: search_public_items_path, local: true, method: :get do |f| %>
          <%= f.text_field :query, placeholder: 'Search', id: 'item_autocomplete' %>
        <% end %>
      </div>
    </ul>
  </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin_header' %>
    <div class='l-body'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/public_header' %>
    <div class='l-body'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>